Repository CuteWebserv/webserv, pull requests merged in 2023-06, with the labels that each got.

#66 feat: MethodHandler member functions about autoindex #65
  .vscode/settings.json
  include/MethodHandler.hpp
  src/HttpProcessor/MethodHandler.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
  src/temp/beforeHttpProcessor.cpp
Labels: feature

#70 Feat/cgi with kqueue#61
  Makefile
  hello.py
  include/Parser.hpp
  include/Server.hpp
  src/Parser/Parser.cpp
  src/Server/Server.cpp
  src/Server/event/error.cpp
  src/Server/event/read.cpp
  src/Server/event/timer.cpp
  src/Server/event/write.cpp
  src/Server/socket/bind.cpp
  src/Server/socket/kqueue.cpp
  src/Server/socket/listen.cpp
  src/Server/socket/setServers.cpp
  src/Server/socket/socket.cpp
Labels: feature

#73 Feat/cgi handler try catch#71
  .vscode/settings.json
  include/CgiHandler.hpp
  src/CgiHandler/CgiHandler.cpp
  src/CgiHandler/main.cpp
Labels: feature

#78 Feat/check memory leaks#77
  include/Server.hpp
  src/Server/event/read.cpp
  src/Server/event/timer.cpp
  src/Server/event/write.cpp
  src/main.cpp
Labels: feature

#81 Feat/create log class#79
  Makefile
  include/Config.hpp
  include/Log.hpp
  include/Server.hpp
  src/Config/Config.cpp
  src/Config/content.cpp
  src/Log/Log.cpp
  src/Server/Server.cpp
  src/Server/socket/bind.cpp
  src/Server/socket/kqueue.cpp
  src/Server/socket/listen.cpp
  src/Server/socket/setServers.cpp
  src/Server/socket/socket.cpp
  src/main.cpp
  src/utils/ft_error.cpp
Labels: feature

#85 Feat/change cout to log#84
  include/CgiHandler.hpp
  src/CgiHandler/CgiHandler.cpp
  src/Config/print.cpp
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/PathFinder.cpp
  src/Parser/Parser.cpp
  src/Server/Server.cpp
  src/Server/event/error.cpp
  src/Server/event/read.cpp
  src/Server/event/timer.cpp
  src/Server/event/write.cpp
  src/utils/ft_split.cpp
Labels: feature

#86 Feat/add cgi python script 초안 #80
  .DS_Store
  include/CgiHandler.hpp
  src/.DS_Store
  src/CgiHandler/CgiHandler.cpp
  src/CgiHandler/a.txt
  src/CgiHandler/bangle.jpg
  src/CgiHandler/get_python.py
  src/CgiHandler/kkambo.jpg
  src/CgiHandler/main.cpp
  src/CgiHandler/post_python.py
  src/CgiHandler/test.html
Labels: feature

#90 fix: GetMethodHandler::methodRun #88
  src/HttpProcessor/MethodHandler.cpp
Labels: bug

#100 Feat/index html만들기#60
  README.md
  data/hi/test.html
  data/index.html
  data/test.htm
  data/test.html
  data/upload/hi/test.html
  data/upload/index.html
  data/upload/testased.html
  include/RequestPool.hpp
  include/Server.hpp
  server.conf
  src/HttpProcessor/MethodHandler.cpp
  src/Parser/Parser.cpp
  src/Server/event/read.cpp
  src/Server/event/timer.cpp
  src/Server/event/write.cpp
Labels: bug, feature, fix

#102 Feat/add caller info#101
  README.md
  include/Log.hpp
  include/Server.hpp
  src/CgiHandler/CgiHandler.cpp
  src/Config/Config.cpp
  src/Config/content.cpp
  src/Config/print.cpp
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/PathFinder.cpp
  src/Log/Log.cpp
  src/Parser/Parser.cpp
  src/Server/Server.cpp
  src/Server/event/error.cpp
  src/Server/event/read.cpp
  src/Server/event/timer.cpp
  src/Server/event/write.cpp
  src/Server/socket/socket.cpp
  src/main.cpp
  src/utils/ft_error.cpp
Labels: feature

#110 fix: error catch # 109
  src/HttpProcessor/HttpProcessor.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
Labels: bug

#113 Feat/cgi connect#106
  .DS_Store
  data/cgi/hello.py
  data/cgi/post_python.py
  data/images/bangle.jpg
  data/images/kkambo.jpg
  data/index.html
  data/upload/index.html
  data/upload/new_file
  data/upload/testased.html
  default.config
  hello.py
  include/Server.hpp
  server.conf
  src/CgiHandler/CgiHandler.cpp
  src/CgiHandler/a.txt
  src/CgiHandler/index.html
  src/CgiHandler/main.cpp
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/MethodHandler.cpp
  src/HttpProcessor/PathFinder.cpp
  src/HttpProcessor/PathTest/Config.cpp
  src/HttpProcessor/PathTest/Config.hpp
  src/HttpProcessor/PathTest/Log.hpp
  src/HttpProcessor/PathTest/Makefile
  src/HttpProcessor/PathTest/Mime.cpp
  src/HttpProcessor/PathTest/Mime.hpp
  src/HttpProcessor/PathTest/PathFinder.cpp
  src/HttpProcessor/PathTest/PathFinder.hpp
  src/HttpProcessor/PathTest/Request.hpp
  src/HttpProcessor/PathTest/ResponseGenerator.cpp
  src/HttpProcessor/PathTest/ResponseGenerator.hpp
  src/HttpProcessor/PathTest/StatusCode.cpp
  src/HttpProcessor/PathTest/StatusCode.hpp
  src/HttpProcessor/PathTest/ValidationStatus.hpp
  src/HttpProcessor/PathTest/a.out
  src/HttpProcessor/PathTest/a/a
  src/HttpProcessor/PathTest/a/b/a
  src/HttpProcessor/PathTest/a/b/b
  src/HttpProcessor/PathTest/content.cpp
  src/HttpProcessor/PathTest/default.conf
  src/HttpProcessor/PathTest/default.config
  src/HttpProcessor/PathTest/ft_config_split.cpp
  src/HttpProcessor/PathTest/ft_error.cpp
  src/HttpProcessor/PathTest/ft_process_print.cpp
  src/HttpProcessor/PathTest/main.cpp
  src/HttpProcessor/PathTest/others/admin/aaa
  src/HttpProcessor/PathTest/others/b/a
  src/HttpProcessor/PathTest/others/d
  src/HttpProcessor/PathTest/print.cpp
  src/HttpProcessor/PathTest/server.conf
  src/HttpProcessor/PathTest/server_content.conf
  src/HttpProcessor/PathTest/utils.hpp
  src/Parser/Parser.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
  src/Server/event/read.cpp
  src/Server/event/timer.cpp
  src/Server/event/write.cpp
Labels: feature

#119 feat: 크롬에서 파일 선택하고 파일 올리기#60
  data/index.html
  src/Parser/Parser.cpp
  src/Server/event/read.cpp
Labels: feature

#121 Fix/chunked body offset#117
  include/ValidationStatus.hpp
  src/Parser/Parser.cpp
Labels: fix

#122 fix: fix error when the directory is not exist #120
  src/HttpProcessor/MethodHandler.cpp
Labels: bug

#131 Refac/parser cpp 리팩토링#125
  Makefile
  include/Parser.hpp
  include/RequestPool.hpp
  src/Parser/Parser.cpp
  src/Parser/parseBody.cpp
  src/Parser/parseChunkedBody.cpp
  src/Parser/parseFirstLine.cpp
  src/Parser/parseHeaders.cpp
  src/Server/event/read.cpp
Labels: fix

#134 fix: /를 붙인 경로 시 오류 해결, autoindex우선 순위 해결 #126
  server.conf
  src/HttpProcessor/MethodHandler.cpp
  src/HttpProcessor/PathFinder.cpp
Labels: bug

#140 Fix/cgi post write pending#139
  data/put_test/tmp_file
  include/CgiHandler.hpp
  include/Server.hpp
  src/CgiHandler/CgiHandler.cpp
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/MethodHandler.cpp
  src/Parser/Parser.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
  src/Server/Server.cpp
  src/Server/event/read.cpp
  src/Server/event/write.cpp
  test.cpp
Labels: fix

#153 refactoring : file separation #150
  Makefile
  include/CgiHandler.hpp
  src/CgiHandler/CgiHandler.cpp
  src/CgiHandler/GetCgiHandler.cpp
  src/CgiHandler/PostCgiHandler.cpp
  src/CgiHandler/env.cpp
Labels: fix

#156 feat: config 파일 유효성 검사 및 공백 추가 #155
  cgi_tester.conf
  include/Config.hpp
  src/Config/Config.cpp
  src/Config/content.cpp
Labels: bug, feature

#162 feat: generate response message with error_page in conf file #158
  .DS_Store
  error_page.html
  include/HttpProcessor.hpp
  src/.DS_Store
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/PathFinder.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
Labels: feature

#165 Fix/kqueue refactor#149
  Makefile
  include/ResponseGenerator.hpp
  include/Server.hpp
  include/beforeHttpProcessor.hpp
  include/utils.hpp
  src/Config/Config.cpp
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/PathFinder.cpp
  src/Parser/Parser.cpp
  src/Parser/parseBody.cpp
  src/Parser/parseChunkedBody.cpp
  src/Parser/parseFirstLine.cpp
  src/Parser/parseHeaders.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
  src/Server/Server.cpp
  src/Server/event/error.cpp
  src/Server/event/read.cpp
  src/Server/event/timer.cpp
  src/Server/event/write.cpp
  src/Server/socket/accept.cpp
  src/main.cpp
  src/utils/ft_strdup.cpp
  src/utils/ft_strjoin.cpp
  src/utils/ft_strlen.cpp
  test/kqueue_cgi/main.cpp
Labels: feature, fix

#172 complete #171
  cgi_tester.conf
  include/MethodHandler.hpp
  src/HttpProcessor/MethodHandler.cpp
Labels: feature

#173 Feat/python cgi post#170
  cgi_tester.conf
  data/cgi/post_test.py
  data/post_test.html
  src/Parser/Parser.cpp
  src/Server/event/write.cpp
Labels: feature, fix

#174 feat: index.html change #169
  cgi_tester.conf
  data/images/bangle_with_note.jpg
  data/index.html
  data/put_test/Screen%20Shot%202023-03-22%20at%206.44.05%20PM.png
Labels: feature

#180 Feat/file write read kqueue#175
  data/put_test/Screen%20Shot%202023-03-22%20at%206.44.05%20PM.png
  data/put_test/default.temp
  include/ResponseGenerator.hpp
  include/Server.hpp
  src/HttpProcessor/MethodHandler.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
  src/Server/Server.cpp
  src/Server/event/read.cpp
  src/Server/event/write.cpp
Labels: feature

#182 Feat/save error page in config#181
  cgi_tester.conf
  data/cgi/post_test.py
  error_page.html
  include/Config.hpp
  include/ResponseGenerator.hpp
  include/Server.hpp
  src/Config/content.cpp
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/PathFinder.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
  src/Server/event/read.cpp
  src/Server/event/timer.cpp
Labels: feature

#184 Fix/fail to send data when timeout#183
  include/ResponseGenerator.hpp
  src/Config/content.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
  src/Server/event/timer.cpp
Labels: feature, fix

#186 refactor: Add openErrorPage function #185
  include/Config.hpp
  src/Config/content.cpp
Labels: refactor

#188 feat: Add printRequestResult function #187
  include/Log.hpp
  src/Log/Log.cpp
  src/Server/event/read.cpp
Labels: feature

#192 ResponseGenerator에서 Response클래스 분리, ResponseGenerator, MethodHandler 리팩토링
  .vscode/settings.json
  include/CgiHandler.hpp
  include/HttpProcessor.hpp
  include/MethodHandler.hpp
  include/PathFinder.hpp
  include/Response.hpp
  include/ResponseGenerator.hpp
  include/Server.hpp
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/MethodHandler.cpp
  src/HttpProcessor/PathFinder.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
Labels: refactor

#193 post와 put에서 index를 보고 파일 이름 우선순위 결정
  cgi_tester.conf
  data/put_test/asdad
  data/put_test/default.temp
  data/put_test/index.html
  data/put_test/sdf
  src/HttpProcessor/MethodHandler.cpp
  src/HttpProcessor/PathFinder.cpp
Labels: bug

#196 fix: change close() in executeCgi() #195
  src/CgiHandler/PostCgiHandler.cpp
Labels: fix

#207 Feat/kqueue leaks#204
  .DS_Store
  .vscode/settings.json
  Makefile
  data/cgi/post_test.py
  data/error_page.html
  include/Log.hpp
  include/Response.hpp
  include/Server.hpp
  src/Config/content.cpp
  src/HttpProcessor/MethodHandler.cpp
  src/Log/Log.cpp
  src/Parser/Server.cpp
  src/Server/Server.cpp
  src/Server/event/client.cpp
  src/Server/event/pipe.cpp
  src/Server/event/process.cpp
  src/Server/event/server.cpp
  src/Server/event/static_file.cpp
  src/Server/event/udata.cpp
  src/Server/socket/accept.cpp
  src/utils/ft_error.cpp
Labels: feature, fix

#210 Fix/print제거#209
  .vscode/settings.json
  data/cgi/post_test.py
  src/Parser/Parser.cpp
  src/Server/Server.cpp
  src/Server/event/client.cpp
  src/Server/event/pipe.cpp
  src/Server/event/server.cpp
  src/Server/event/static_file.cpp
  src/Server/event/udata.cpp
Labels: fix, refactor

#211 Refactor/assign a udata to a request#208
  Makefile
  default.conf
  include/Log.hpp
  include/PathFinder.hpp
  include/Server.hpp
  src/Config/content.cpp
  src/HttpProcessor/PathFinder.cpp
  src/Server/Server.cpp
  src/Server/event/client.cpp
  src/Server/event/pipe.cpp
  src/Server/event/process.cpp
  src/Server/event/server.cpp
  src/Server/event/static_file.cpp
  src/Server/event/udata.cpp
  src/Server/socket/socket.cpp
Labels: fix, refactor

#213 refactor: cgi response 를 그대로 활용 #212
  include/ResponseGenerator.hpp
  src/ResponseGenerator/ResponseGenerator.cpp
Labels: refactor
