Repository CuteWebserv/webserv, pull requests merged in 2023-05, with the labels that each got.

#24 feat: Remove cpplint.yml
  .github/workflows/cpplint.yml
Labels: feature

#25 fix: file path 경로 수정
  src/Config/Config.cpp
  src/main.cpp
Labels: bug

#26 Style/modify code convention#22
  include/Parser.hpp
  include/Request.hpp
  include/RequestPool.hpp
  include/StatusCode.hpp
  include/ValidationStatus.hpp
  src/Parser/Parser.cpp
  src/Parser/main.cpp
Labels: feature

#28 Feat/config file data vaild and struct change#13
  Makefile
  include/Config.hpp
  include/Server.hpp
  include/utils.hpp
  server.conf
  server_content.conf
  src/Config/Config.cpp
  src/Config/content.cpp
  src/Config/get.cpp
  src/Config/print.cpp
  src/Server/Server.cpp
  src/main.cpp
  src/utils/ft_config_split.cpp
  src/utils/ft_error.cpp
  src/utils/ft_process_print.cpp
  src/utils/ft_split.cpp
  src/utils/ft_strdup.cpp
  src/utils/ft_strjoin.cpp
  src/utils/ft_strlen.cpp
  src/utils/ft_strtrim.cpp
  src/utils/ft_toLower.cpp
Labels: feature, fix

#34 feat: class HttpProcessor #33
  .DS_Store
  include/ErrorResponse.hpp
  include/HttpProcessor.hpp
  include/MethodHandler.hpp
  include/ResponseGenerator.hpp
  src/.DS_Store
  src/ErrorResponse/ErrorResponse.cpp
  src/HttpProcessor/HttpProcessor.cpp
  src/HttpProcessor/MethodHandler.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
Labels: feature

#40 Fix/add some members to config hpp#39
  include/Config.hpp
  server_content.conf
  src/Config/content.cpp
Labels: fix

#42 fix: create a response class and fix some of Makefile
  Makefile
  include/HttpProcessor.hpp
  include/MethodHandler.hpp
  include/Response.hpp
  include/ResponseGenerator.hpp
  src/Response/Response.cpp
Labels: fix

#49 Feat/create response class#43
  .vscode/settings.json
  include/MethodHandler.hpp
  include/Response.hpp
  include/StatusCode.hpp
  src/HttpProcessor/MethodHandler.cpp
  src/Response/Response.cpp
Labels: feature

#53 feat: cgi 이벤트 처리 인터페이스 구현 #31
  include/Server.hpp
  src/Server/Server.cpp
  src/utils/ft_split.cpp
Labels: feature

#56 Feat/check max body size#54
  Makefile
  include/Parser.hpp
  server.conf
  src/Parser/Parser.cpp
  src/Server/Server.cpp
Labels: feature

#57 feat : multi port multi server_block 적용 #55
  Makefile
  include/Parser.hpp
  include/RequestPool.hpp
  include/Server.hpp
  server.conf
  src/Parser/Parser.cpp
  src/Server/Server.cpp
  src/Server/bind.cpp
  src/Server/listen.cpp
  src/Server/setServers.cpp
  src/Server/socket.cpp
Labels: feature

#63 doc : add default.conf for example #62
  default.config
Labels: documentation

#64 Feat/create MethodHandler, create ResponseGenerator #37
  .vscode/settings.json
  Makefile
  include/MethodHandler.hpp
  include/Mime.hpp
  include/Response.hpp
  include/ResponseGenerator.hpp
  include/Server.hpp
  include/StatusCode.hpp
  include/beforeHttpProcessor.hpp
  src/HttpProcessor/MethodHandler.cpp
  src/Response/Response.cpp
  src/ResponseGenerator/Mime.cpp
  src/ResponseGenerator/ResponseGenerator.cpp
  src/ResponseGenerator/StatusCode.cpp
  src/Server/Server.cpp
  src/temp/beforeHttpProcessor.cpp
  test/a.txt
Labels: feature
